version: '3'

services:
  db:
    container_name: meuMySQL
    image: mysql
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    
   